### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by brianveltman** [dkuk/modal_windows#2]
Can you explain how to use this?

**Comment by dkuk** [comment]
As per Readme.md :)
It generates a pair: link with appropriate div. If it uses option {:modal_type => 'permanent'} then modal window just opens to show static content (second arg of helper). It can be closed by button.
Second way is like
link_to_modal_window('Show modal with dynamic loaded content', {:controller => 'docflow_versions', :action=> 'autocomplete_for_user', :q => ''})
It loads content by targeted href to div. Content displays on every link click, but loads once - on first click while div content is empty. This type of window disappears on mouseleave or mouse click outside of this popup window. 
It is not very functional, but we use it for micro-forms, tips or displaying some extended information on page.

**Comment by brianveltman** [comment]
can you give me an example? for instance how to use it on a wiki with an url?

**Comment by dkuk** [comment]
I think it will be a problem because of wiki generates full page (not a partial). Such link loads whole page with css, JS and so on. I am on the phone now and can't check. Look around of wiki pages - is any posibilty of partial generation without layout and try direct link on such page
link_to_modal_window( 'Wiki info', ''project/wiki/partial_page" )
of course, you cant try with any link, it works (if no specific JS conflicts) but looks ugly
